; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri Apr 10 2020 21:58:05 GMT-0600 (Mountain Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


