; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri Apr 10 2020 21:58:05 GMT-0600 (Mountain Daylight Time)
M280 P5 S10 ; deploy BLTouch

