; sleep.g
; called when M1 (Sleep) is being processed
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri Apr 10 2020 21:58:05 GMT-0600 (Mountain Daylight Time)

; Shut off heaters and motors
M18 ; disable steppers
M106 S0 ; turn off cooling fan
M104 S0 ; set hotend to 0
M140 S0 ; set bed to 0